In [ ]:
#testing for the gpu

!nvidia-smi

Mon Mar 18 18:53:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#00_pytorch_fundamentals    
 https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


#introduction to tensors

In [ ]:
##creating tensors

#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#getting tensor back as a python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix

matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor

tensor = torch.tensor([[[1,2,4],
                        [3,6,9],
                        [9,8,7]]])
tensor

tensor([[[1, 2, 4],
         [3, 6, 9],
         [9, 8, 7]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 4],
        [3, 6, 9],
        [9, 8, 7]])

In [ ]:
hd = torch.tensor([[[[1,2,3,4],
                     [4,7,8,9]]]])
hd

tensor([[[[1, 2, 3, 4],
          [4, 7, 8, 9]]]])

In [ ]:
hd.shape

torch.Size([1, 1, 2, 4])

In [ ]:
hd[0][0][1][2]

tensor(8)

#random tensors

they are important because the way many neural networks learn is that they start with tensors full of random numbers and then they adjust those random numbers to better represent the data.

In [ ]:
#create a random tensor
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3973, 0.3614, 0.6026, 0.0274],
         [0.9869, 0.4242, 0.9629, 0.4333],
         [0.0825, 0.5632, 0.1844, 0.2328]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.1053, 0.8663, 0.2276],
         [0.5117, 0.2319, 0.8874],
         [0.7008, 0.6536, 0.0634],
         ...,
         [0.9558, 0.4984, 0.4366],
         [0.3639, 0.3639, 0.2315],
         [0.6604, 0.0771, 0.5981]],

        [[0.6829, 0.0915, 0.5569],
         [0.9753, 0.3653, 0.6067],
         [0.5815, 0.1859, 0.7187],
         ...,
         [0.5778, 0.5173, 0.4112],
         [0.1893, 0.3990, 0.0372],
         [0.2197, 0.5893, 0.8704]],

        [[0.8000, 0.6596, 0.3064],
         [0.5695, 0.5281, 0.7335],
         [0.3459, 0.0872, 0.9582],
         ...,
         [0.0919, 0.7347, 0.1861],
         [0.0072, 0.6967, 0.5392],
         [0.0620, 0.2727, 0.8347]],

        ...,

        [[0.4328, 0.8753, 0.6707],
         [0.4607, 0.9658, 0.3621],
         [0.3264, 0.1299, 0.1430],
         ...,
         [0.3894, 0.3714, 0.7968],
         [0.2496, 0.9353, 0.9793],
         [0.1442, 0.4560, 0.4445]],

        [[0.7231, 0.8474, 0.7571],
         [0.8493, 0.0367, 0.6024],
         [0.

In [ ]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

In [ ]:
#creating tensors in a range

torch.range(0,10)

<ipython-input-30-4d6181ba4d58>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(start=0,end=1100,step=77)
one_to_ten

tensor([   0,   77,  154,  231,  308,  385,  462,  539,  616,  693,  770,  847,
         924, 1001, 1078])

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensor like
one_to_eleven = torch.zeros_like(one_to_ten)
one_to_eleven

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one_to_nine = torch.ones_like(one_to_ten)
one_to_nine

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#tensor datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #even if we mentioned None, the default value is set to float32

torch.float32

In [ ]:
#changing the datatype
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

#important parameters while creating tensors

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= None, #datatype
                               device= None, #what device is your tensor on,bydefault=cpu
                               requires_grad= False) #weather or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
/float_16_tensor * float_32_tensor  #why no error when the datatypes are different

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#using long dtype
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor  #still works, its robust

tensor([ 9., 36., 81.])

In [ ]:
 #getting information from tensor attributes

display(float_32_tensor.shape)
display(float_32_tensor.dtype)
display(float_32_tensor.device)

torch.Size([3])

torch.float32

device(type='cpu')

In [ ]:
#create a tensor
some_tensor = torch.rand([3,4],dtype= torch.float16)
some_tensor

tensor([[0.6226, 0.2998, 0.0762, 0.7051],
        [0.9556, 0.0918, 0.3628, 0.1450],
        [0.6860, 0.3081, 0.2925, 0.2026]], dtype=torch.float16)

In [ ]:
some_tensor.shape , some_tensor.size

(torch.Size([3, 4]), <function Tensor.size>)

In [ ]:
some_tensor.size()  #.shape is an attribute and .size is a function, they do the same job.

torch.Size([3, 4])

In [ ]:
#find out the details about the tensor
print(some_tensor)
print(f'datatype of the tensor is : {some_tensor.dtype}')
print(f'shape of the tensor: {some_tensor.shape}')
print(f'device the tensor is on: {some_tensor.device}')

tensor([[0.4028, 0.2290, 0.1528, 0.6064],
        [0.4077, 0.4536, 0.5820, 0.3164],
        [0.9917, 0.1396, 0.9956, 0.3369]], dtype=torch.float16)
datatype of the tensor is : torch.float16
shape of the tensor: torch.Size([3, 4])
device the tensor is on: cpu


#Manipulating tensors or TENSOR OPERATIONS

addition , subtraction , multiplication , division , matrix multiplication


In [ ]:
#create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
#this does not change the original tensor
#to change the original tensor, we have to reassign it

tensor = tensor+10
tensor

tensor([21, 22, 23])

In [ ]:
tensor

tensor([21, 22, 23])

In [ ]:
tensor - 10

tensor([11, 12, 13])

In [ ]:
#PyTorch inbuilt functions

torch.mul(tensor , 10)

tensor([210, 220, 230])

In [ ]:
tensor

tensor([21, 22, 23])

In [ ]:
torch.add(tensor , 10)

tensor([31, 32, 33])

In [ ]:
torch.sub(tensor , 10)

tensor([11, 12, 13])

#Matrix Multiplication

two ways of performing multiplication in nueral networks and deep learning;


 -- element wise multiplication

 -- matrix multiplication (dot product)

In [ ]:
#element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, '*',tensor)
print(f'equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication - inbuilt function
torch.matmul(tensor,tensor) #dot prod; 1+4+9=14

tensor(14)

In [ ]:
#comparing the time
%%time
value = 0
for i in range(len(tensor)): #[1,2,3]
  value+= tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 2.29 ms, sys: 56 µs, total: 2.34 ms
Wall time: 6.91 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

In [ ]:
#one of the most common errors in Deep Learning is shape errors

In [ ]:
tensor@tensor #@ is a symbol for matrix multiplication

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) #does not work because the inner dim does not match


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# no error because inner dim are same
# the resultant matrix has the shape of the outer dimensions

torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.2716, 0.4681],
        [0.4174, 0.5410]])

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3798, 1.0004, 1.1834],
        [0.4338, 1.0549, 1.1103],
        [0.2882, 0.7662, 0.9174]])

In [ ]:
torch.matmul(torch.rand(10,3), torch.rand(3,10))

tensor([[0.5851, 0.0998, 0.2531, 0.3633, 0.2506, 0.3532, 0.2689, 0.3390, 0.1917,
         0.2275],
        [1.1615, 0.3018, 0.5630, 0.4880, 0.4466, 0.4849, 0.4174, 0.9267, 0.3985,
         0.4909],
        [0.7589, 0.2529, 0.2865, 0.3062, 0.2397, 0.2988, 0.2126, 0.6447, 0.3961,
         0.3193],
        [1.6706, 0.5513, 0.5778, 0.7350, 0.5193, 0.7115, 0.4750, 1.3641, 0.9263,
         0.6911],
        [1.4407, 0.2837, 0.7432, 0.7126, 0.6198, 0.7063, 0.6175, 1.0109, 0.3702,
         0.5939],
        [2.2604, 0.6693, 0.8847, 1.0211, 0.7725, 0.9955, 0.7257, 1.7836, 1.0763,
         0.9352],
        [1.1446, 0.2845, 0.3794, 0.6758, 0.4098, 0.6492, 0.4293, 0.7387, 0.5765,
         0.4458],
        [1.3515, 0.4314, 0.6475, 0.4413, 0.4685, 0.4439, 0.3968, 1.2281, 0.5379,
         0.5908],
        [1.3056, 0.4141, 0.5982, 0.4576, 0.4483, 0.4564, 0.3868, 1.1580, 0.5477,
         0.5646],
        [1.9467, 0.6154, 0.8071, 0.7696, 0.6511, 0.7568, 0.5808, 1.6505, 0.9089,
         0.8246]])

In [ ]:
#shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A , tensor_B) #torch.mm is same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# we cannot multiply these because their inner dimensions are not the same, so to fix this
# we can transpose these.
# by transposing, we manipulate the shape of the one of the tensors


In [ ]:
tensor_B.T , tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
print(f'the original shapes: tensor A = {tensor_A.shape}, tensor B = {tensor_B.shape}')
print(f'New shapes: tensor A = {tensor_A.shape} is the same, tensor B = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.shape} inner dimensions must match ')
print('output \n')
output = torch.mm(tensor_A , tensor_B.T)
print(output)
print(f'\noutput shape: {output.shape}')



the original shapes: tensor A = torch.Size([3, 2]), tensor B = torch.Size([3, 2])
New shapes: tensor A = torch.Size([3, 2]) is the same, tensor B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) inner dimensions must match 
output 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])


In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

#tensor aggregation

finding the min, max, mean , sum , etc


In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.dtype  #torch.int64 is a long datatype

torch.int64

In [ ]:
#find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean
torch.mean(x) #got the error because the mean function cannot work with a long datatype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean() #alternatively

tensor(45.)

In [ ]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#argmin and argmax
x.argmin()  #index of the min value

tensor(0)

In [ ]:
x.argmax()  ##index of the max value

tensor(9)

In [ ]:
x[0] , x[9]

(tensor(0), tensor(90))

#reshaping , stacking , squeezing and unsqueezing tensors

view - return a view of an input tensor of certain shape but keep the same memory as the original tensor

stacking - combine multiple tensors on the top of the other stack(vstack) or side by side(hstack).

squeeze - removes all 1 dimensions from the tensor.

unsqueeze - add a 1 dimension to the target tensor

permute - return a view of the input with dimensions permuted in a certain way

In [ ]:
#create a tensor

x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension by using reshape

x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view

z = x.view(1,9) #changing z changes x because the view of a tensor shares the same memory as the original input
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=2) #because the original shape of x is incompatible with changing the dim to 2
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [66]:
#squeeze - removes all the single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_reshaped.shape

torch.Size([1, 9])

In [65]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
print(f'previous tensor:{x_reshaped}')
print(f'previous shape:{x_reshaped.shape}')

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nnew tensor: {x_squeezed}')
print(f'new shape: {x_squeezed.shape}')

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])

new tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [73]:
#torch unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f'previous target: {x_squeezed}')
print(f'previous shape: {x_squeezed.shape}')

#add an extra dimension with the unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nnew tensor: {x_unsqueezed}')
print(f'new tensor: {x_unsqueezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

new tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new tensor: torch.Size([1, 9])


In [75]:
# for another dim

#torch unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f'previous target: {x_squeezed}')
print(f'previous shape: {x_squeezed.shape}')

#add an extra dimension with the unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nnew tensor: {x_unsqueezed}')
print(f'new tensor: {x_unsqueezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

new tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new tensor: torch.Size([9, 1])


In [78]:
# torch.permute - reaaranges the dimensions of a target tensor in a specified order.

x_original = torch.rand(size=(224,224,3)) #height,width,color channels

#permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2 , 0 , 1)

print(f'previous shape: {x_original.shape}')
print(f'new shape: {x_permuted.shape}') #color channels, height, weight

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [81]:
x_original[0,0,0] = 10

In [84]:
x_permuted[0,0,0]

tensor(10.)

#Indexing

In [86]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
x[0]  #targets the outer bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
#targets on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [89]:
x[0][0][0] #targets the inner bracket

tensor(1)

In [92]:
x[1][1][1] #because the first dim ran out, it can only give 0

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [95]:
x[:,0]

tensor([[1, 2, 3]])

In [96]:
x[:,:,1]

tensor([[2, 5, 8]])

In [97]:
x[:,1,1]

tensor([5])

In [98]:
x[0,0,:]

tensor([1, 2, 3])

In [101]:
#index on x to return 9
#index on x to return 3,6,9
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [102]:
x[:,2,2]

tensor([9])

In [103]:
x[:,:,2]

tensor([[3, 6, 9]])

#PyTorch and Numpy

Numpy is a popular scientific Python numerical computing library.

and because of this, Pytorch has functionality to interact with it.

data in numpy,want it in Tensor --> torch.from_numpy(ndarray)

PyTorch tensor, in NumPy --> torch.tensor.numpy()

In [104]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [105]:
#why tensor dtype is float64?
#because the default numpy array dtype is float64 and PyTorch reflects that in the tensor
array.dtype

dtype('float64')

In [107]:
#changing the data type
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [108]:
#change the value of array , it doesn't chnge the value of the tensor

array = array+1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [110]:
#tensor to numpy

tensor = torch.ones(9)
numpy_tensor = tensor.numpy()

tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
numpy_tensor.dtype

dtype('float32')

In [112]:
#change the value of tensor, numpy tensor remains the same.

tensor = tensor+1
numpy_tensor

tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#PyTorch Reproducibility


trying to take the random out of the random.

In [113]:
torch.rand(3,3)

tensor([[0.2892, 0.9250, 0.9060],
        [0.7588, 0.6132, 0.4194],
        [0.8783, 0.9250, 0.0317]])

In [114]:
#random seed adds flavour to the randomness.

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6499, 0.1114, 0.2684, 0.7832],
        [0.2595, 0.5063, 0.8186, 0.7166],
        [0.7415, 0.2738, 0.2199, 0.5393]])
tensor([[0.3880, 0.3552, 0.5832, 0.3692],
        [0.6369, 0.2100, 0.0253, 0.7033],
        [0.5259, 0.1655, 0.7611, 0.3474]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [117]:
# making random but reproducible tensors

#set the random seed
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [118]:
#still no random numbers matched , so we can used random seed before calling the random tensors


random_seed = 42
torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
# random seed makes torch.rand reproducibility
#refer to PyTorch.org reproducibility

#Different ways of accessing GPUs for faster computations


GPU = Faster computation on numbers

getting a GPU:
* google colab GPU for free
* own GPU setup
* use cloud computing

In [119]:
import torch
torch.cuda.is_available()

False

In [121]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [122]:
#count the number of devices
torch.cuda.device_count()

0

In [123]:
#create a tensor(on CPU)
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [124]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [125]:
#moving back to cpu
tensor_on_gpu.numpy() #to fix errors


array([1, 2, 3])

In [126]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])